# Generated by Django 5.0.7 on 2024-07-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_timestamp_alter_song_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 18, 28, 46, 798793)),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 18, 28, 46, 798793)),
        ),
    ]
