# Generated by Django 5.0.7 on 2024-07-18 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_alter_song_timestamp_alter_song_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 18, 9, 48, 35, 616696)),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 18, 9, 48, 35, 616696)),
        ),
    ]
